In [1]:
print("Hello")

Hello


In [2]:
print("Hello how are You !!")

Hello how are You !!


In [4]:
def helo():
    print("return from helo")

In [5]:
helo()

return from helo


In [6]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [27]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

NameError: name 'np' is not defined

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [13]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [15]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [16]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
arr=np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
arr=np.ones((6,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
arr = np.linspace(0, 10, 100)#liner space between 2 numbers
print(arr)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

Random Generation function

when value is coming from 0 to 1 this is called normalizations and when value is coming from -3 to 3 this is called standerizations

In [ ]:
np.random.rand(10) # this is normalizations value is coming from -1 to 1

array([0.14590122, 0.71164038, 0.10299099, 0.85299541, 0.83992009,
       0.85807203, 0.94096884, 0.19444105, 0.30075765, 0.10678142])

In [ ]:
np.random.randn(10)  # this is standerizations value is coming from -3 to 3

array([-0.18949898, -1.95764274,  2.20359354,  0.79769928,  1.60268902,
       -1.86519858,  0.46940115,  1.20673027,  0.99531818,  0.71996918])

In [16]:
np.random.randint(10,20)

11

In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8],[8,9,9,10]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9,  9, 10]])

In [12]:
arr.shape    # return how many rows and how many column

(3, 4)

In [13]:
arr.size   # return total size how many element  

12

In [14]:
arr.dtype  # return which type

dtype('int64')

Array Methods 

In [15]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9,  9, 10]])

In [17]:
arr.max()

np.int64(10)

In [18]:
arr.min()

np.int64(1)

In [19]:
arr.sum()

np.int64(72)

In [ ]:
np.sum(arr,axis=0)   # column wise sum

array([14, 17, 19, 22])

In [ ]:
np.sum(arr,axis=1)   # row wise sum

array([10, 26, 36])

In [24]:
arr.mean()

np.float64(6.0)

In [25]:
arr.std()

np.float64(2.857738033247041)

Reshape and resizing

In [31]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
arr=arr.reshape(5,6)

In [38]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

Indexing and slicing 

In [40]:
arr=np.arange(11,30,2)

In [41]:
arr

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [42]:
arr[5]

np.int64(21)

In [43]:
arr[0:]

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [44]:
arr[1:7]

array([13, 15, 17, 19, 21, 23])

In [45]:
arr[2::2]

array([15, 19, 23, 27])

Indexing and Sliceing for a Matrix

In [47]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [49]:
arr_reshape=arr[0:3,1:4]
arr_reshape

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16]])

In [52]:
slice=arr[2:,4:]
slice

array([[17, 18],
       [23, 24],
       [29, 30]])

Some Extra Arraay Operations

In [54]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [55]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [56]:
a2-a1

array([5, 5, 5, 5, 5])

In [57]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [58]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [59]:
a1//a2

array([0, 0, 0, 0, 0])

In [60]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Multiplications

In [62]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [63]:
A

array([[1, 2],
       [3, 4]])

In [64]:
B

array([[5, 6],
       [7, 8]])

In [65]:
A@B

array([[19, 22],
       [43, 50]])

In [66]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [67]:
A.T

array([[1, 3],
       [2, 4]])

In [68]:
B.T

array([[5, 7],
       [6, 8]])